name: Docker Image CI/CD

on:
  push:
    branches:  
      - master 

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./gsr-mirror

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - name: Image Build Push
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
        registry: ghcr.io
        repository: platformercloud/git-mirror
        tag_with_ref: true
