name: Docker Image CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/platformercloud/git-mirror-gsr
      CONTAINER_REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output
          name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build the Docker image
        run: docker build --tag
          ${SERVICE_NAME}:latest --file
          Dockerfile /gsr-mirror
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:latest
         